#!/bin/bash

# deploy the zimlet
su - zimbra -c "zmzimletctl -l deploy /opt/zimbra/zimlets-extra/tk_barrydegraaff_zimbra_openpgp.zip"

#remove zimlet install flag
grep -v "pgp-zimlet" /tmp/zimlet-install > /tmp/zimlet-install.post.pgp-zimlet
mv /tmp/zimlet-install.post.pgp-zimlet /tmp/zimlet-install

#execute mailboxd restart if no flags are left
if [ "$(wc -l < /tmp/zimlet-install)" -eq 0 ]; then
   su - zimbra -c 'zmprov fc all && zmmailboxdctl restart'
fi
